name: Build

on:
  push:
    branches: 
    - main
    - dev
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - name: Test the extension
        run: |
          npm install
          npm run lint
      - name: Build the extension
        run: |
          npm run dist
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jpl
          path: |
            package.json
            publish
            README.md
